apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
type: Opaque
data:
  # Paste the encoded strings here (NO QUOTES needed)
  AWS_ACCESS_KEY_ID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  AWS_SECRET_ACCESS_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
